ALTER TABLE loans
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE reservations
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'PENDING';

ALTER TABLE book_copies
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE';

ALTER TABLE fines
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'OPEN';
